version: "3.4"

services:
  ganache:
    build:
      dockerfile: ../deploy/Ganache/Dockerfile
      context: ../blockchain
    ports:
      - 8545:8545
    networks:
      - backend

  truffle:
    build:
      dockerfile: ../deploy/Truffle/Dockerfile
      context: ../blockchain
    depends_on:
      - ganache
    networks:
      - backend
    volumes:
      - .:/app
      - /home/app/node_modules
    restart: on-failure:5

  app:
    build:
      context: ../app
      dockerfile: ../deploy/App/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - ganache
    networks:
      - backend

networks:
  backend:
    driver: bridge
